//! Local persistence: settings, recent list, projects (JSON files in the app data dir).

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use knorozov_core::models::{Quality, DEFAULT_MIRROR};
use knorozov_core::transcript::Transcript;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Settings {
    pub save_dir: String,
    pub mirror: String,
    /// "light" | "dark" | "system"
    pub theme: String,
    pub language: String,
    pub quality: Quality,
    pub diarize: bool,
    pub first_run_done: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            save_dir: String::new(),
            mirror: DEFAULT_MIRROR.into(),
            theme: "light".into(),
            language: "auto".into(),
            quality: Quality::Fast,
            diarize: false,
            first_run_done: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentItem {
    pub id: String,
    pub name: String,
    pub format: String,
    /// Unix ms
    pub created_at: i64,
    pub duration_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub id: String,
    pub name: String,
    pub source_path: String,
    /// File used by the in-app player (the source, or a WAV copy for formats WebViews can't play).
    pub media_path: String,
    pub format: String,
    pub created_at: i64,
    pub quality: Quality,
    pub transcript: Transcript,
}

pub struct Store {
    pub root: PathBuf,
}

fn write_atomic(path: &Path, data: &[u8]) -> Result<()> {
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, data)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

impl Store {
    pub fn new(root: PathBuf) -> Result<Self> {
        fs::create_dir_all(root.join("projects"))?;
        fs::create_dir_all(root.join("models"))?;
        fs::create_dir_all(root.join("playback"))?;
        Ok(Self { root })
    }
    pub fn models_dir(&self) -> PathBuf {
        self.root.join("models")
    }
    pub fn playback_dir(&self) -> PathBuf {
        self.root.join("playback")
    }
    fn settings_path(&self) -> PathBuf {
        self.root.join("settings.json")
    }
    fn recent_path(&self) -> PathBuf {
        self.root.join("recent.json")
    }
    fn project_path(&self, id: &str) -> PathBuf {
        // ids are generated by us, but never trust path components
        let safe: String = id.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '-').collect();
        self.root.join("projects").join(format!("{safe}.json"))
    }

    pub fn load_settings(&self) -> Settings {
        fs::read(self.settings_path())
            .ok()
            .and_then(|b| serde_json::from_slice(&b).ok())
            .unwrap_or_default()
    }
    pub fn save_settings(&self, s: &Settings) -> Result<()> {
        write_atomic(&self.settings_path(), &serde_json::to_vec_pretty(s)?)
    }

    pub fn recent(&self) -> Vec<RecentItem> {
        fs::read(self.recent_path())
            .ok()
            .and_then(|b| serde_json::from_slice(&b).ok())
            .unwrap_or_default()
    }
    fn save_recent(&self, items: &[RecentItem]) -> Result<()> {
        write_atomic(&self.recent_path(), &serde_json::to_vec_pretty(items)?)
    }

    pub fn save_project(&self, p: &Project) -> Result<()> {
        write_atomic(&self.project_path(&p.id), &serde_json::to_vec(p)?)?;
        let mut items = self.recent();
        items.retain(|r| r.id != p.id);
        items.insert(
            0,
            RecentItem {
                id: p.id.clone(),
                name: p.name.clone(),
                format: p.format.clone(),
                created_at: p.created_at,
                duration_ms: p.transcript.duration_ms,
            },
        );
        self.save_recent(&items)
    }

    pub fn update_project(&self, p: &Project) -> Result<()> {
        write_atomic(&self.project_path(&p.id), &serde_json::to_vec(p)?)
    }

    pub fn load_project(&self, id: &str) -> Result<Project> {
        let b = fs::read(self.project_path(id)).context("расшифровка не найдена")?;
        Ok(serde_json::from_slice(&b)?)
    }

    pub fn delete_project(&self, id: &str) -> Result<()> {
        if let Ok(p) = self.load_project(id) {
            let media = PathBuf::from(&p.media_path);
            if media.starts_with(self.playback_dir()) {
                fs::remove_file(media).ok();
            }
        }
        fs::remove_file(self.project_path(id)).ok();
        let mut items = self.recent();
        items.retain(|r| r.id != id);
        self.save_recent(&items)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip() {
        let dir = std::env::temp_dir().join(format!("kp-store-{}", std::process::id()));
        let st = Store::new(dir.clone()).unwrap();
        let mut s = st.load_settings();
        assert_eq!(s.mirror, DEFAULT_MIRROR);
        s.theme = "dark".into();
        st.save_settings(&s).unwrap();
        assert_eq!(st.load_settings().theme, "dark");
        let p = Project {
            id: "20261006-1".into(),
            name: "Интервью.mp3".into(),
            source_path: "/x/Интервью.mp3".into(),
            media_path: "/x/Интервью.mp3".into(),
            format: "mp3".into(),
            created_at: 1,
            quality: Quality::Fast,
            transcript: Transcript::default(),
        };
        st.save_project(&p).unwrap();
        assert_eq!(st.recent()[0].name, "Интервью.mp3");
        assert_eq!(st.load_project("20261006-1").unwrap().name, "Интервью.mp3");
        st.delete_project("20261006-1").unwrap();
        assert!(st.recent().is_empty());
        fs::remove_dir_all(dir).ok();
    }
}
